#! /usr/bin/env bash
FORMAT=$(cat $HOME/.config/polybar/modules/calendar/dateformat.conf)
DATE="$(date +"${FORMAT}")"

case "$1" in
--popup)
     bash $HOME/.config/polybar/modules/calendar/naivecalendar.sh

   ;;
--format)
    bash $HOME/.config/polybar/modules/calendar/dateformat_controller.sh
    ;;
*)
    #echo  ${DATE}
    echo ${DATE}

    ;;
esac
