[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x4c4c4c"
blue = "0xb8b8b8"
cyan = "0xa16946"
green = "0x383838"
magenta = "0xe8e8e8"
red = "0xdc9656"
white = "0xfeffff"
yellow = "0x484848"

[colors.cursor]
cursor = "0xeeeeee"
text = "0x282828"

[colors.normal]
black = "0x282828"
blue = "0xb3deef"
cyan = "0x73cef4"
green = "0xc9d05c"
magenta = "0xd3b987"
red = "0xf43753"
white = "0xeeeeee"
yellow = "0xffc24b"

[colors.primary]
background = "0x282828"
foreground = "0xeeeeee"

[font]
size = 8.5

[font.normal]
family = "DejaVuSansM Nerd Font"

[window]
opacity = 0.9
title = ""
dynamic_title = false
