# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ 
	(modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { 
	device = "/dev/disk/by-uuid/dca6ec1f-fe48-4484-abc5-feee60c01ce4";
        fsType = "ext4";
    };

  fileSystems."/boot" =
    { 
	device = "/dev/disk/by-uuid/C3FB-7248";
        fsType = "vfat";
    };

  swapDevices =
    [ 
	{ 
	    device = "/dev/disk/by-uuid/1348785d-6da6-45b0-89bc-1aff676f7851"; 
	}
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  #hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  hardware = {
	#cpu.intel.updateMicrocode = true;
        cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

	enableAllFirmware = true;
	opengl = {
		enable = true;
		extraPackages = with pkgs; [vaapiIntel libvdpau-va-gl vaapiVdpau ];
	};
	bluetooth.enable = true;
#	pulseaudio.enable = true;
  };

}
